<?php

/* -------------------------------------------------------
 *
 *   LiveStreet Engine Social Networking
 *   Copyright © 2008 Mzhelskiy Maxim
 *
 * --------------------------------------------------------
 *
 *   Official site: www.livestreet.ru
 *   Contact e-mail: rus.engine@gmail.com
 *   Kazkakh language file - translated by Nurzhol Tabigat
 *   mail to: nurzhol.t@gmail.com
 *
 *   GNU General Public License, version 2:
 *   http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 *
  ---------------------------------------------------------
 */

/**
 * Қазақ тілінің файлы
 * Жүйедегі барлық текстті қамтиды.
 */
return array(
	/**
	 * Блогтар
	 */
	'blogs' => 'Блогтар',
	'blogs_search_title_hint' => 'Атауларды іздеу',
	'blogs_search_empty' => 'Іздеу нәтиже бермеді',
	'blogs_title' => 'Атауы',
	'blogs_readers' => 'Оықрман саны',
	'blogs_rating' => 'Рейтинг',
	'blogs_owner' => 'Бақылаушы',
	'blogs_personal_title' => 'Блог иесі -',
	'blogs_personal_description' => 'Бұл сіздің жеке блогыңыз.',
	'blog_closed' => 'Жабық блог',
	'blog_no_topic' => 'Бұл жерде әзірге ештеңе жарияланбаған',
	'blog_rss' => 'RSS лента',
	'blog_rating' => 'Рейтинг',
	'blog_vote_count' => 'дауыс',
	'blog_about' => 'Блог туралы',
	'blog_expand_info' => 'Толығырақ &darr;',
	'blog_fold_info' => 'Жинау &uarr;',
	/**
	 * Declensions
	 */
	'reader_declension' => 'оқырман;оқырман;оқырман',
	'topic_declension' => 'тақырып;тақырып;тақырып',
	'draft_declension' => 'нобай;нобай;нобай',
	/**
	 * Танымал блогтар
	 */
	'blog_popular' => 'Танымал блогтар',
	'blog_popular_rating' => 'Рейтинг',
	'blog_popular_all' => 'барлық блог',
	/**
	 * Блог қолданушылары
	 */
	'blog_user_count' => 'жазылушы',
	'blog_user_administrators' => 'Админ',
	'blog_user_moderators' => 'Модератор',
	'blog_user_moderators_empty' => 'Модератор тағайындалмаған',
	'blog_user_readers' => 'Оқырмандар',
	'blog_user_readers_all' => 'Блогтың барлық оқырмандары',
	'blog_user_readers_empty' => 'Оқырмандар әзірге жазылмаған',
	/**
	 * Блогқа дауыс беру
	 */
	'blog_vote_up' => 'ұнайды',
	'blog_vote_down' => 'ұнамайды',
	'blog_vote_count_text' => 'дауыс бергендер:',
	'blog_vote_error_already' => 'Бұл блогқа дауыс бергенсіз',
	'blog_vote_error_self' => 'Өз блогыңызға дауыс бере алмайсыз',
	'blog_vote_error_acl' => 'Рейтингіңіз төмен, дауыс бере алмайсыз',
	'blog_vote_error_close' => 'Жабық блогқа дауыс бере алмайсыз',
	'blog_vote_ok' => 'Дауыс бергеніңізге рақмет',
	/**
	 * Блогқа кіру және шығу
	 */
	'blog_join' => 'блогқа кіру',
	'blog_join_ok' => 'Блогқа кірдіңіз',
	'blog_join_error_invite' => 'Бұл блогқа шақыртумен ғана кіре аласыз!',
	'blog_join_error_self' => 'Бұл өз блогыңыз ғой!',
	'blog_leave' => 'блогтан шығу',
	'blog_leave_ok' => 'Блогтан шықтыңыз',
	'blog_join_leave' => 'Кіру/Шығу',
	/**
	 * Блог мәзірі
	 */
	'blog_menu_all' => 'Барлығы',
	'blog_menu_all_good' => 'Қызықтылар',
	'blog_menu_all_discussed' => 'Талқылудағылар',
	'blog_menu_all_top' => 'TOP',
	'blog_menu_all_new' => 'Жаңа',
	'blog_menu_all_list' => 'Барлық блог',
	'blog_menu_collective' => 'Ұжымдық',
	'blog_menu_collective_good' => 'Қызықты',
	'blog_menu_collective_new' => 'Жаңа',
	'blog_menu_collective_discussed' => 'Талқылаудағылар',
	'blog_menu_collective_top' => 'TOP',
	'blog_menu_personal' => 'Жеке',
	'blog_menu_personal_good' => 'Жақсы',
	'blog_menu_personal_new' => 'Жаңа',
	'blog_menu_personal_discussed' => 'Талқылаудағылар',
	'blog_menu_personal_top' => 'TOP',
	'blog_menu_top_period_24h' => '24 сағаттық',
	'blog_menu_top_period_7d' => '7 күндік',
	'blog_menu_top_period_30d' => '30 күндік',
	'blog_menu_top_period_all' => 'Барлығы',
	'blog_menu_create' => 'Блог',
	/**
	 * Блогты жасау/өзгерту
	 */
	'blog_edit' => 'Өзгерту',
	'blog_delete' => 'Жою',
	'blog_create' => 'Жаңа блог ашу',
	'blog_create_acl' => 'Блог жасауға рейтингіңіз жетпейді',
	'blog_create_title' => 'Блог атауы',
	'blog_create_title_notice' => 'Блог атауын дұрыс жазыңызН.',
	'blog_create_title_error' => 'Блог атауы 2-ден 200-ге дейін символ арасында болуы керек',
	'blog_create_title_error_unique' => 'Бұндай атауы бар блог бұрын ашылған екен',
	'blog_create_url' => 'Блогқа URL',
	'blog_create_url_notice' => 'Блогқа өткенде, сайт адресінен соң көрсетілегін URL. Тек қана латын әріптері мен сандардан, дефистен, ал бос орындар "_" белгісіне ауысады. Мағынасы бойынша, URL блог атауына сәйкескені дұрыс. Бұл параметрді сақтаған соң, өзгертуге болмайды.',
	'blog_create_url_error' => 'Блог URL-ы 2-ден 50-ге дейін ғана символдан құралуы керек + сандар мен "-", "_" белгілері',
	'blog_create_url_error_badword' => 'Блог URL-ы өзгеше болсын:',
	'blog_create_url_error_unique' => 'Бұндай URL бұрыннан бар',
	'blog_create_description' => 'Блог сипаттамасы',
	'blog_create_description_notice' => 'HTML-тегтер қолдана аласыз',
	'blog_create_description_error' => 'Блогты сипаттау тексті, 10-3000 символ арасында болуы керек.',
	'blog_create_type' => 'Блог типі',
	'blog_create_type_open' => 'Ашық',
	'blog_create_type_close' => 'Жабық',
	'blog_create_type_open_notice' => 'Ашық — бұндай блогқа әркім қосылып, мақалаларын барлығы оқи алады.',
	'blog_create_type_close_notice' => 'Жабық — бұндай блогқа әркім қосыла алмайды, мақалаларын тек блог мүшелері ғана оқи алады',
	'blog_create_type_error' => 'Белгісіз блог типі',
	'blog_create_rating' => 'Рейтинг бойынша шектеуі',
	'blog_create_rating_notice' => 'Бұл блогқа жазу үшін, қолданушыға қажет рейтинг',
	'blog_create_rating_error' => 'Рейтинг белгісі сан болуы керек',
	'blog_create_avatar' => 'Аватар',
	'blog_create_avatar_error' => 'Аватар жүктелінбеді',
	'blog_create_avatar_delete' => 'жою',
	'blog_create_submit' => 'сақтау',
	'blog_create_submit_notice' => '«Сақтау» батырмасын басқан соң, блог ашылады',
	/**
	 * Блогты басқару
	 */
	'blog_admin' => 'Блогты басқару',
	'blog_admin_not_authorization' => 'Блогты өөзгерту үшін, өз аккаунтыңызбен кіріңіз.',
	'blog_admin_profile' => 'Профайл',
	'blog_admin_users' => 'Қолданушылар',
	'blog_admin_users_administrator' => 'админ',
	'blog_admin_users_moderator' => 'модератор',
	'blog_admin_users_reader' => 'оқырман',
	'blog_admin_users_bun' => 'бан алған',
	'blog_admin_users_current_administrator' => 'Бұл сіз &mdash; нағыз админ!',
	'blog_admin_users_empty' => 'блогта ешкім жоқ',
	'blog_admin_users_submit' => 'сақтау',
	'blog_admin_users_submit_notice' => '«Сақтау» батырмасын басқан соң, қолданушылар бапатуы сақталады',
	'blog_admin_users_submit_ok' => 'Баптау сақталды',
	'blog_admin_users_submit_error' => 'Қате',
	'blog_admin_delete_title' => 'Блогты жою',
	'blog_admin_delete_confirm' => 'Блогты өшіресіз бе?',
	'blog_admin_delete_move' => 'Мақалаларды блогқа көшіру',
	'blog_delete_clear' => 'Мақалаларды өшіру',
	'blog_admin_delete_success' => 'Блог жойылды',
	'blog_admin_delete_not_empty' => 'Жазбасы бар блогты өшіре алмайсыз. Алдын-ала блоктағы жазбаларды өшіріңіз.',
	'blog_admin_delete_move_error' => 'Өшірілетін блогтан мақалалар көшпеді',
	'blog_admin_delete_move_personal' => 'Мақалаларды жеке блогқа көшіруге болмайды',
	'blog_admin_user_add_label' => 'Қолданушылар қосу',
	'blog_admin_user_invited' => 'Шақырылғандар тізімі',
	'blog_admin_user_add_header' => 'Қолданушыларды шақыру',
	'blog_admin_user_add_empty' => 'Шақырылғандар жоқ',
	'blog_close_show' => 'Бұл жабық блог, контентін қарауға құқығыңыз жоқ',
	'blog_user_invite_add_self' => 'Өз өзіңізді шақыра алмайсыз',
	'blog_user_invite_add_ok' => '%%login%% атты қолданушыға шақырту жіберілді',
	'blog_user_invite_remove_ok' => '%%login%% атты қолданушы шақыртуы өшірілді',
	'blog_user_already_invited' => '%%login%% атты қолданушыға шақырту жіберілген',
	'blog_user_already_exists' => '%%login%% атты қолданушы блогта бар',
	'blog_user_already_reject' => '%%login%% атты қолданушы шақыртуды қабылдамады',
	'blog_user_invite_title' => "'%%blog_title%%' блогының оқырманы болуға шақыру",
	'blog_user_invite_text' => "%%login%% атты қолданушы, сізді '%%blog_title%%' блогының оқырманы болуға шақыруда.<br/><br/><a href='%%accept_path%%'>Қабылдау</a> - <a href='%%reject_path%%'>Қабылдамау</a>",
	'blog_user_invite_already_done' => 'Бұрыннан бұл блогтың оқырманысыз',
	'blog_user_invite_accept' => 'Шақырту қабылданды',
	'blog_user_invite_reject' => 'Шақырту қабылданбады',
	'blog_user_invite_readd' => 'қайталау',
	'blog_user_invite_remove' => 'жою',
	/**
	 * Мақалалар
	 */
	'topic_title' => 'Мақалалар',
	'topic_read_more' => 'Толығырақ',
	'topic_author' => 'Мақала авторы',
	'topic_date' => 'уақыты',
	'topic_tags' => 'Тегтер',
	'topic_tags_empty' => 'жоқ',
	'topic_user' => 'авторлық текст',
	'topic_share' => 'Бөлісу',
	'topic_time_limit' => 'Өте жиі мақала жариялауға болмайды',
	'topic_comment_read' => 'пікірлерді оқу',
	'topic_comment_add' => 'Пікір қалдыру',
	'topic_comment_add_title' => 'пікір жазу',
	'topic_comment_add_text_error' => 'Пікір тексті 2-3000 символ арасында болуы керек',
	'topic_comment_acl' => 'Пікір жазуға, рейтингіңіз жетпейді',
	'topic_comment_limit' => 'Өте жиі пікір қалдыруға болмайды',
	'topic_comment_notallow' => 'Мақала авторы пікір жазуға тыйым салды',
	'topic_comment_spam' => 'Стоп! Спам!',
	'topic_unpublish' => 'мақала нобайда',
	'topic_favourite_add' => 'таңдаулыға қосу',
	'topic_favourite_add_ok' => 'Мақала таңдаулыға қосылды',
	'topic_favourite_add_no' => 'Бұл мақала сіздің таңдаулылар қатарыңызда жоқ',
	'topic_favourite_add_already' => 'Таңдаулылар қатарында бұрыннан бар',
	'topic_favourite_del' => 'таңдаулы қатарынан өшіру',
	'topic_favourite_del_ok' => 'Мақала таңдаулы қатарынан өшті',
	'topic_favourite_tags_block' => 'Таңдаулылар тегтері',
	'topic_favourite_tags_block_all' => 'Барлық тегтер',
	'topic_favourite_tags_block_user' => 'Менің тегтерім',
	'error_favorite_topic_is_draft' => 'Нобайдағы мақаланы таңдаулылар қатарына қосуға болмайды',
	'block_stream_comments_all' => 'Барлық пікір эфирі',
	'block_stream_topics_all' => 'Барлық мақала эфирі',
	'comments_all' => 'Барлық пікірлер',
	'add_favourite_tags' => 'Өз тегімді қосамын',
	/**
	 * Мақалалар мәзірі
	 */
	'topic_menu_add' => 'Мақала',
	'topic_menu_add_topic' => 'Тексттік',
	'topic_menu_add_question' => 'Сауалнама',
	'topic_menu_add_link' => 'Сілтеме',
	'topic_menu_add_photoset' => 'Фотосет',
	'topic_menu_saved' => 'Нобай',
	'topic_menu_published' => 'Жарияланған',
	/**
	 * Мақала жариялау
	 */
	'topic_topic_create' => 'Мақала жариялау',
	'topic_topic_edit' => 'Мақаланы өзгерту',
	'topic_create' => 'Жазу',
	'topic_create_blog' => 'Қай блогқа жариялаймыз?',
	'topic_create_blog_personal' => 'жеке блогым',
	'topic_create_blog_error_unknown' => 'Белгісіз блогқа жарияламақсыз ба?',
	'topic_create_blog_error_nojoin' => 'Бұл блогта жоқсыз!',
	'topic_create_blog_error_noacl' => 'Бұл блогқа жариялау үшін, рейтингіңіз жеткіліксіз',
	'topic_create_blog_error_noallow' => 'Бұл блогқа жаза алмайсыз',
	'topic_create_blog_notice' => 'Белгілі бір блогқа жазу үшін, сол блогқа кіру керексіз.',
	'topic_create_title' => 'Атауы',
	'topic_create_title_notice' => 'Мақала атауы, оның мазмұнын сипаттай алатын болғаны дұрыс.',
	'topic_create_title_error' => 'Мақала атауы 2-200 символ арасында болуы керек',
	'topic_create_text' => 'Текст',
	'topic_create_text_notice' => 'html-тегтер бар',
	'topic_create_text_error' => 'Мақала тексті 2-15000 символ арасында болуы керек',
	'topic_create_text_error_unique' => 'Бұндай атауы бар мақала жазғансыз',
	'topic_create_type_error' => 'Мақала типі қате',
	'topic_create_tags' => 'Тегтер',
	'topic_create_tags_notice' => 'Тегтерді үтір арқылы бөліп жазасыз. Мысалы: google, Астана, ақпарат',
	'topic_create_tags_error_bad' => 'Тегтердің дұрыстығын тексеріңіз',
	'topic_create_tags_error' => 'Мақала тегтері 2-50 символ арасында, жалпы ұзындығы 500 символдан аспауы керек',
	'topic_create_forbid_comment' => 'Пікір жазуға тыйым салу',
	'topic_create_forbid_comment_notice' => 'Осы жерді белгілесеңіз, мақалаңызға ешкім пікір қалдыра алмайды',
	'topic_create_publish_index' => 'Алғашқы бетке шығару',
	'topic_create_publish_index_notice' => 'Осыны белгілесеңіз, ох чудо амиго, мақала алғашқы бетке секіріп кетеді. Тек админ амигоға берілетін мүмкіндік қо.',
	'topic_create_submit_publish' => 'Жариялау',
	'topic_create_submit_save' => 'Нобайға сақтау',
	'topic_create_submit_preview' => 'Алдын ала қарау',
	'topic_create_submit_preview_close' => 'жинау',
	'topic_create_submit_notice' => '«Нобайға сақтау» батырмасын бассаңыз, тақырыбында құлып бейнеленген мақала тек өзіңізге ғана көрінетін болады. Мақала барлығына көрінуі үшін, «Жариялау» батырмасын басыңыз.',
	'topic_create_notice' => 'Назар аударыңыз: кілтсөз <cut> ұзын мәтінді қысқартып, «Толығырақ» сілтемесінің орналастырады. <cut> кілтсөзі қойылған жерге дейін жалпы парақта көрініп, әрі қарайғы мәтіні парақ толық ашылғанға дейін жасырын орналасады',
	'topic_create_error' => 'Мақаланы қосуда қате туындады. Кейінірек қайта көріңіз.',
	'topic_edit' => 'Өзгерту',
	'topic_preview' => 'Алдын ала көру',
	'topic_delete' => 'Жою',
	'topic_delete_confirm' => 'Мақаланы шынымен өшіргіңіз келеді ме?',
	/**
	 * Мақала-сілтеме
	 */
	'topic_link' => 'мақала-сілтеме',
	'topic_link_title' => 'Сілтемелер',
	'topic_link_title_edit' => 'Сілтемені өзгерту',
	'topic_link_title_create' => 'Сілтеме қосу',
	'topic_link_create' => 'Сілтеме-мақала жариялау',
	'topic_link_edit' => 'Сілтеме-мақаланы өзгерту',
	'topic_link_count_jump' => 'сілтеме бойынша өту',
	'topic_link_create_url' => 'Сілтеме',
	'topic_link_create_url_notice' => 'Мысалы, http://livestreet.ru/blog/dev_livestreet/113.html',
	'topic_link_create_url_error' => 'Сілтеме 2-200 символ аралығында болуы керек.',
	'topic_link_create_text' => 'Қысқа сипаттамасы (максимум 500 символ)',
	'topic_link_create_text_notice' => 'HTML-тегтер тыйым салынған',
	'topic_link_create_text_error' => 'Сілтеме сипаттамасы 10-500 символ аралығында болуы керек',
	/**
	 * Сауалнама-мақала
	 */
	'topic_question_title' => 'Сауалнамалар',
	'topic_question_title_edit' => 'Сауалнаманы өзгерту',
	'topic_question_title_create' => 'Сауалнама құру',
	'topic_question_vote' => 'дауыс беру',
	'topic_question_vote_ok' => 'Даусыңыз саналды.',
	'topic_question_vote_already' => 'Даусыңыз саналған',
	'topic_question_vote_result' => 'Нәтиже',
	'topic_question_vote_result_sort' => 'Сорттауды қосу\өшіру',
	'topic_question_abstain' => 'қатыспау',
	'topic_question_abstain_result' => 'Қатыспағандар',
	'topic_question_create' => 'Сауалнама-мақала құру',
	'topic_question_edit' => 'Сауалнама-мақаланы өзгерту',
	'topic_question_create_title' => 'Сауал',
	'topic_question_create_title_notice' => 'Сауалнаманы барынша қысқа да нұсқа етуге тырысыңыз.',
	'topic_question_create_title_error' => 'Сауал 2-200 символ арасында болуы керек',
	'topic_question_create_answers' => 'Жауап нұсқалары',
	'topic_question_create_answers_add' => 'Нұсқа қосу',
	'topic_question_create_answers_delete' => 'Жою',
	'topic_question_create_answers_error' => 'Жауап 1-100 символ арасында болуы керек',
	'topic_question_create_answers_error_min' => 'Жауап нұсқасы кемінде екеу болуы керек',
	'topic_question_create_answers_error_max' => 'Ең көп жауап нұсқа саны 20 болуы керек',
	'topic_question_create_text' => 'Қысқаша сипаттамасы (максимум 500 символ)',
	'topic_question_create_text_notice' => 'HTML-тегтерге тыйым салынады',
	'topic_question_create_text_error' => 'Сауалнама сипаттамасы 500 символдан аспасын',
	/**
	 * Мақалаға дауыс беру
	 */
	'topic_vote_up' => 'ұнайды',
	'topic_vote_down' => 'ұнамайды',
	'topic_vote_error_already' => 'Дауыс беріп қойғансыз',
	'topic_vote_error_self' => 'з мақалаңызға дауыс бере алмайсыз',
	'topic_vote_error_guest' => 'дауыс беру үшін, сайтқа кіріңіз',
	'topic_vote_error_time' => 'Мақалаға дауыс беру уақыты аяқталды',
	'topic_vote_error_acl' => 'Дауыс бері үшін, күш пен рейтнг жеткіліксіз',
	'topic_vote_no' => 'әзірге ешкім дауыс бермеген',
	'topic_vote_ok' => 'Даусыңыз саналды',
	'topic_vote_ok_abstain' => 'Мақала рейтингін қараудан тыс қалдыңыз',
	'topic_vote_count' => 'барлық дауыс бергендер',
	/**
	 * Фотосет
	 */
	'topic_photoset_create' => 'Фотосет жасау',
	'topic_photoset_edit' => 'Фотосетті өзгерту',
	'topic_photoset_upload_title' => 'Сурет жүктеу',
	'topic_photoset_upload_choose' => 'Сурет жүктеу',
	'topic_photoset_upload_close' => 'Жабу',
	'topic_photoset_upload_rules' => 'Суреттердің JPG, PNG, GIF форматтары ғана рұқсат етілген<br />Сурет өлшемі %%SIZE%% Kб-тан аспасын<br />Максималды сурет саны: %%COUNT%%',
	'topic_photoset_choose_image' => 'Жүктейтін суретті таңдаңыз',
	'topic_photoset_is_preview' => 'Мақаланың басты суреті ретінде тағайындалды',
	'topic_photoset_mark_as_preview' => 'Басты сурет ретінде тағайындау',
	'topic_photoset_show_all' => 'Барлық %%COUNT%% суретті көрсету',
	'topic_photoset_count_images' => 'сурет;сурет;сурет',
	'topic_photoset_show_more' => 'Тағы да сурет көрсету',
	'topic_photoset_error_count_photos' => 'Мақалада %%MIN%% - %%MAX%% аралығында сурет бола алады',
	'topic_photoset_error_size' => 'Сурет өлшемі тым үлкен',
	'topic_photoset_title' => 'Фотосет',
	'topic_photoset_photo_deleted' => 'Сурет жойылды',
	'topic_photoset_photo_deleted_error_last' => 'Соңғы суретті жоя алмаймыз',
	'topic_photoset_photo_delete' => 'Жою',
	'topic_photoset_photo_delete_confirm' => 'Суретті жоясыз ба?',
	'topic_photoset_photo_added' => 'Сурет қосылды',
	'topic_photoset_error_too_much_photos' => 'Мақалаға %%MAX%% санына көп сурет салуға болмайды',
	'topic_photoset_title_edit' => 'Фотосетті өңдеу',
	'topic_photoset_title_create' => 'фотосет жасау',
	'topic_photoset_error_bad_filesize' => 'Сурет өлшемі %%MAX%% Кб-тан көп болмасын',
	'topic_photoset_photos' => 'сурет',
	/**
	 * Пікірлер
	 */
	'comment_title' => 'Пікірлер',
	'comment_target_author' => 'авторы',
	'comment_count_new' => 'Жаңа пікірлер саны',
	'comment_url_notice' => 'Пікірге сілтеме',
	'comment_collapse' => 'жинау',
	'comment_expand' => 'жаю',
	'comment_goto_parent' => 'Жауап:',
	'comment_goto_child' => 'Жауапқа оралу',
	'comment_bad_open' => 'пікірді ашу',
	'comment_answer' => 'Жауап беру',
	'comment_delete' => 'Жою',
	'comment_delete_ok' => 'Пікір жойылды',
	'comment_repair' => 'Қылпына келтіру',
	'comment_repair_ok' => 'Пікір қалпына келді',
	'comment_was_delete' => 'пікір жойылды',
	'comment_add' => 'қосу',
	'comment_preview' => 'алдын ала қарау',
	'comment_unregistered' => 'Тек қана сайтқа кірген қолданушылар ғана пікір қалдыра алады.',
	'comment_subscribe' => 'жаңа пікір болса, ескерту алу',
	'comment_declension' => 'пікір;пікір;пікір',
	/**
	 * Пікірге ауыс беру
	 */
	'comment_vote_error' => 'Кейінірек дауыс беріңіз',
	'comment_vote_error_value' => '+1 немесе -1 ғана дауыс беруге болады',
	'comment_vote_error_acl' => 'Дауыс беруге рейтингіңіз жеткіліксіз',
	'comment_vote_error_already' => 'Бұл пікірге дауыс бергенсіз',
	'comment_vote_error_time' => 'Бұл пікірге дауыс беру уақыты аяқталды',
	'comment_vote_error_self' => 'Өз пікіріңізге дауыс бере алмайсыз',
	'comment_vote_error_noexists' => 'Жоқ пікірге дауыс беріп жатырсыз!',
	'comment_vote_ok' => 'Даусыңыз саналды',
	'comment_favourite_add' => 'таңдаулы қатарына қосу',
	'comment_favourite_add_ok' => 'Пікір таңдаулылар қатарына қосылды',
	'comment_favourite_add_no' => 'Бұл пікір таңдаулылар қатарында жоқ',
	'comment_favourite_add_already' => 'Бұл пікір таңдаулылар қатарында бар',
	'comment_favourite_del' => 'таңдаулылардан өшіру',
	'comment_favourite_del_ok' => 'Пікір таңдаулылар қатарынан өшті',
	/**
	 * Амиголар
	 */
	'people' => 'Амиголар',
	/**
	 * Қолданушы
	 */
	'user' => 'Қолданушы',
	'user_list' => 'Қолданушылар',
	'user_list_new' => 'Жаңа қолданушылар',
	'user_list_online_last' => 'Сайтта жақында болғандар',
	'user_good' => 'Позитивтілер',
	'user_bad' => 'Негативтілер',
	'user_privat_messages' => 'Хат',
	'user_privat_messages_new' => 'Жаңа хат бар',
	'user_settings' => 'Баптаулар',
	'user_settings_profile' => 'профайл',
	'user_settings_tuning' => 'сайт',
	'user_login' => 'Логин немесе пошта',
	'user_login_submit' => 'Кіру',
	'user_login_remember' => 'Жүйеде сақтау',
	'user_login_bad' => 'Қате. Логин, (e-mail) немесе құпиясөз дұрыс жазылмаған.',
	'user_not_activated' => 'Логиніңізді белсенді етпедіңіз. <br/> <a href="%%reactivation_path%%">Белсенді етуге сұраныс жіберу</a>',
	'user_password' => 'Құпиясөз',
	'user_password_reminder' => 'Құпиясөзді еске түсіру',
	'user_exit_notice' => 'Рақмет! Келіп тұрасыз деген ойдамыз.',
	'user_authorization' => 'Кіру',
	'user_registration' => 'Тіркелу',
	'user_write_prvmsg' => 'Хат жазу',
	'user_friend_add' => 'Дос қатарына қосу',
	'user_friend_add_ok' => 'Жаңа дос қосылды',
	'user_friend_add_self' => 'Сіздің досыңыз - өзіңіз!',
	'user_friend_del' => 'Дос қатарынан жою',
	'user_friend_del_ok' => 'Бұл досыңыз жойылды',
	'user_friend_del_no' => 'Дос табылмады!',
	'user_friend_offer_reject' => 'Сұраныс орындалмады',
	'user_friend_offer_send' => 'Сұраныс жіберілді',
	'user_friend_already_exist' => 'Қолданушы бұрыннан дос қатарында',
	'user_friend_offer_title' => '%%login%% атты қолданушы сізбен дос болғысы келеді.',
	'user_friend_offer_text' => "%%login%% атты қолданушы сізбен дос болғысы келеді.<br/><br/>%%user_text%%<br/><br/><a href='%%accept_path%%'>Қабылдау</a> - <a href='%%reject_path%%'>Қабылдамау</a>",
	'user_friend_add_deleted' => 'Бұл қолданушы дос болудан бас тартты',
	'user_friend_add_text_label' => 'Өзіңізді таныстырыңыз:',
	'user_friend_add_submit' => 'Жіберу',
	'user_friend_add_cansel' => 'Болдырмау',
	'user_friend_add_time_limit' => 'Өте жиі хат жіберіп жатырсыз, дос болуға сұранысты кейінірек жіберуге тырысыңыз',
	'user_friend_offer_not_found' => 'Сұраныс табылмады',
	'user_friend_offer_already_done' => 'Сұраныс өңделді',
	'user_friend_accept_notice_title' => 'Сұраныс қабылданды',
	'user_friend_accept_notice_text' => '%%login%% атты қолданушы сізбен дос болуға келісті',
	'user_friend_reject_notice_title' => 'Сұраныс қабылданбады',
	'user_friend_reject_notice_text' => '%%login%% атты қолданушы сізбен дос болуға келіспеді',
	'user_friend_del_notice_title' => 'Сізді дос қатарынан өшірді',
	'user_friend_del_notice_text' => 'Сіздегі %%login%% атты қолданушы, дос қатарынан жойылды',
	'user_rating' => 'Рейтинг',
	'user_skill' => 'Күш',
	'user_date_last' => 'Соңғы кірген уақыты',
	'user_date_registration' => 'Тіркелген күні',
	'user_empty' => 'бұндай жоқ',
	'user_stats' => 'Статистика',
	'user_stats_all' => 'Барлық қолданушы',
	'user_stats_active' => 'Белсенділер',
	'user_stats_noactive' => 'Адасқандар',
	'user_stats_sex_man' => 'Ерлер',
	'user_stats_sex_woman' => 'Қатындар',
	'user_stats_sex_other' => 'Жынысы көрсетілмеген',
	'user_not_found' => 'Қолданушы <b>%%login%%</b> табылмады',
	'user_not_found_by_id' => 'Қолданушы <b>%%login%%</b> табылмады',
	'user_search_title_hint' => 'Логині бойынша іздеу',
	'user_search_filter_all' => 'Барлығы',
	'user_search_empty' => 'Іздегеніңіз табылмады',
	'user_status_online' => 'Желіде',
	'user_status_offline' => 'Желіде емес',
	/**
	 * Қолданушы профайл мәзірі
	 */
	'people_menu_users' => 'Қолданушылар',
	'people_menu_users_all' => 'Барлығы',
	'people_menu_users_online' => 'Желідегілер',
	'people_menu_users_new' => 'Жаңалар',
	/**
	 * Тіркелу
	 */
	'registration_invite' => 'Шақырту бойынша тіркелу',
	'registration_invite_code' => 'Тіркелу коды',
	'registration_invite_code_error' => 'Шақырту коды қате',
	'registration_invite_check' => 'Кодты тексеру',
	'registration_activate_ok' => 'Құтты болсын! Аккаунтыңыз мақұлданды.',
	'registration_activate_error_code' => 'Мақұлдау коды қате',
	'registration_activate_error_reactivate' => 'Аккаунтыңыз мақұлданған',
	'registration_confirm_header' => 'Аккаунтты мақұлдау',
	'registration_confirm_text' => 'Тіркелуді жасадыңыз, енді аккаунтты мақұлдау қажет. Тіркелу кезінде жазған поштаңызға, мақұлдау нұсқаулыңы жіберілді.',
	'registration' => 'Тіркелу',
	'registration_is_authorization' => 'Тіркелу жасалып, мақұлдау орындалып қойған!',
	'registration_login' => 'Логин',
	'registration_login_error' => 'Қате. Логин 3-30 символ аралығында ғана болсын',
	'registration_login_error_used' => 'Бұл логин бұрыннан бар',
	'registration_login_notice' => 'Тек қана әріптерден (A-Z a-z), сандардан (0-9) құрала алады. Белгі (_) символын қолданбай-ақ қойған дұрыс. Логин 3-30 символ аралығында болуы керек.',
	'registration_mail' => 'E-mail',
	'registration_mail_error' => 'E-mail форматы қате',
	'registration_mail_error_used' => 'Бұл e-mail тіркелген',
	'registration_mail_notice' => 'Қауіпсіздік мақсатында, e-mail қажет.',
	'registration_password' => 'Құпиясөз',
	'registration_password_error' => 'Қате, құпиясөз кемі 5 символдан құралуы керек',
	'registration_password_error_different' => 'Құпиясөздер  сәйкеспейді',
	'registration_password_notice' => 'Құпиясөз 5 символан кем болмасын, логинмен сәйкеспесін. Оңай құпиясөз қолданбаңыз.',
	'registration_password_retry' => 'Құпиясөзді қайталаңыз',
	'registration_captcha' => 'Сандар мен әріптерді жазыңыз',
	'registration_captcha_error' => 'Код қате',
	'registration_submit' => 'Тіркелу',
	'registration_ok' => 'Құтты болсын! Тіркелу сәтті болды',

	/**
	 * Мақұлдау сұранысын қайта орындау
	 */
	"reactivation" => "Мақұлдау сұранысын қайта орындау",
	"reactivation_submit" => "Мақұлдау сілтемесін алу",
	"reactivation_send_link" => "Мақұлдау сілтемесі электронды поштаңызға жіберілді.",

	/**
	 * Қолданушыға дауыс беру
	 */
	'user_vote_up' => 'ұнайды',
	'user_vote_down' => 'ұнамайды',
	'user_vote_error_already' => 'Қолданушыға дауыс бергенсіз',
	'user_vote_error_self' => 'Өз өзіңізге дауыс бере алмайсыз',
	'user_vote_error_guest' => 'дауыс беру үшін, сайтқа кіріңіз',
	'user_vote_error_acl' => 'Дауыс беруге күш пен рейтинг жеткіліксіз',
	'user_vote_ok' => 'Даусыңыз саналды',
	'user_vote_count' => 'дауыс',
	/**
	 * Қолданушы профилінің мәзірі
	 */
	'user_menu_profile' => 'Профайл',
	'user_menu_profile_whois' => 'Ақпарат',
	'user_menu_profile_wall' => 'Профайл парағы',
	'user_menu_profile_friends' => 'Достары',
	'user_menu_profile_stream' => 'Белсенділігі',
	'user_menu_profile_notes' => 'Ескертпелер',
	'user_menu_profile_favourites' => 'Таңдаулылар',
	'user_menu_profile_favourites_topics' => 'Таңдаулы мақалалар',
	'user_menu_profile_favourites_comments' => 'Таңдаулы пікірлер',
	'user_menu_profile_tags' => 'Ескертпелер',
	'user_menu_publication' => 'Жарияланымдар',
	'user_menu_publication_blog' => 'Блог',
	'user_menu_publication_comment' => 'Пікірлер',
	'user_menu_publication_comment_rss' => 'RSS лента',
	/**
	 * Профайл
	 */
	'profile_privat' => 'Жеке',
	'profile_contacts' => 'Контактілер',
	'profile_social' => 'Аккаунттар',
	'profile_sex' => 'Жынысы',
	'profile_sex_man' => 'ер',
	'profile_sex_woman' => 'қатын',
	'profile_birthday' => 'Туылған күні',
	'profile_place' => 'Қайдан',
	'profile_about' => 'Қолданушы туралы ақпарат',
	'profile_site' => 'Сайты',
	'profile_activity' => 'Белсенділігі',
	'profile_friends' => 'Достары',
	'profile_friends_self' => 'Достары',
	'profile_invite_from' => 'Шақырушылар',
	'profile_invite_to' => 'Шықарылғандар',
	'profile_blogs_self' => 'Ашқандары',
	'profile_blogs_join' => 'Мүшелік етеді',
	'profile_blogs_moderation' => 'Модераторлық етеді',
	'profile_blogs_administration' => 'Админдік етеді',
	'profile_date_registration' => 'Тіркелген уақыты',
	'profile_date_last' => 'Соңғы кіруі',
	'profile_social_contacts' => 'Контактілері мен әлеуметтік желілері',
	'profile_add_friend' => 'Дос қатарын толықтыру',
	'profile_user_follow' => 'Назарда ұстаймын',
	'profile_user_unfollow' => 'Назарда ұстамаймын',
	/**
	 * UserFields
	 */
	'user_field_admin_title' => 'Қолданушының контакт алаңы',
	'user_field_admin_title_add' => 'Алаңша қосамын',
	'user_field_add' => 'Қосамын',
	'user_field_cancel' => 'Болдырмаймын',
	'user_field_added' => 'Мән қосылды',
	'user_field_update' => 'Өзгерту',
	'user_field_updated' => 'Алаңша өзгерді',
	'user_field_delete' => 'Жою',
	'user_field_delete_confirm' => 'Алаңшаны өшіресіз бе?',
	'user_field_deleted' => 'Алаңша жойылды',
	'userfield_form_name' => 'Атауы',
	'userfield_form_type' => 'Типі',
	'userfield_form_title' => 'Тақырыбы',
	'userfield_form_pattern' => 'Шаблон (мән {*} токен түрінде ұсынылады)',
	'user_field_error_add_no_name' => 'Алаңша атауын жазыңыз',
	'user_field_error_add_no_title' => 'Алаңша тақырыбын жазыңыз',
	'user_field_error_name_exists' => 'Мұндай атаудағы алаңша бұрыннан бар',
	/**
	 * Қолданушы ескерпесі
	 */
	'user_note_form_edit' => 'Өзгерту',
	'user_note_form_delete' => 'Жою',
	'user_note_form_save' => 'Сақтау',
	'user_note_form_cancel' => 'Болдармау',
	'user_note_add' => 'Ескертпе жазу',
	'user_note_save_error' => 'Қате',
	'user_note_target_error' => 'Қолданушы қатесі',
	'user_note_list_empty' => 'Бұнда ештеңе жоқ',
	/**
	 * Жеке парақ
	 */
	'wall_add_pid_error' => 'Бұл хатқа жауап беру мүмкін емес',
	'wall_add_error' => 'Жеке параққа жазба жазу мүмкін емес',
	'wall_add_time_limit' => 'Жеке параққа өте жиі жазуға болмайды',
	'wall_add_title' => 'Жеке параққа жазба қалдыру',
	'wall_add_submit' => 'Жіберу',
	'wall_add_quest' => 'Жеке параққа жазба қалдыру үшін, тіркелу керек.',
	'wall_list_empty' => 'Жеке парақта жазба жоқ, алғашқы болыңыз!',
	'wall_load_more' => 'Алдыңғв жазбаларға',
	'wall_load_reply_more' => 'Барлығын көрсету',
	'wall_action_delete' => 'Жою',
	'wall_action_reply' => 'Болдырмау',
	'wall_reply_placeholder' => 'Жауап беру...',
	'wall_reply_submit' => 'Жіберу',
	/**
	 * Баптаулар
	 */
	'settings_profile_edit' => 'Профайлды өзгерту',
	'settings_profile_section_base' => 'Негізгі ақпарат',
	'settings_profile_section_contacts' => 'Контактілер',
	'settings_profile_name' => 'Атауы',
	'settings_profile_name_notice' => 'Атау ұзындығы 2-20 символ аралығында болсын.',
	'settings_profile_mail' => 'E-mail',
	'settings_profile_mail_error' => 'Енгізілген e-mail форматы қате',
	'settings_profile_mail_error_used' => 'Бұл e-mail бұрыннан қолданыста',
	'settings_profile_mail_notice' => 'Сіздің шын e-mail адресіңіз, осыған ескертулер келеді.',
	'settings_profile_mail_change_from_notice' => 'Жаңа e-mail ауыстыру үшін, ескі e-mail-ыңызға мақұлдау хаты жіберілді',
	'settings_profile_mail_change_to_notice' => 'Рақмет! <br/> Жаңа e-mail ауыстыру үшін, ескі e-mail-ыңызға мақұлдау хаты жіберілді',
	'settings_profile_mail_change_ok' => 'Жаңа e-mail-ыңыз <b>%%mail%%</b> болды',
	'settings_profile_sex' => 'Жыныс',
	'settings_profile_sex_man' => 'ер',
	'settings_profile_sex_woman' => 'қатын',
	'settings_profile_sex_other' => 'айтпаймын',
	'settings_profile_birthday' => 'Туған күн',
	'settings_profile_country' => 'Мемлекет',
	'settings_profile_city' => 'Қала',
	'settings_profile_icq' => 'ICQ',
	'settings_profile_site' => 'Сайт',
	'settings_profile_site_url' => 'Сайт URL',
	'settings_profile_site_name' => 'сайт атауы',
	'settings_profile_about' => 'Өзіңіз туралы ақпарат',
	'settings_profile_password_current' => 'Қазіргі құпиясөз',
	'settings_profile_password_current_error' => 'Қазіргі құпиясөз қате',
	'settings_profile_password_new' => 'Жаңа құпиясөз',
	'settings_profile_password_new_error' => 'Қате, құпиясөз кемі 5 символдан құралсын',
	'settings_profile_password_confirm' => 'Жаңа құпиясөзді қайта жазыңыз',
	'settings_profile_password_confirm_error' => 'Құпиясөздер сәйкеспейді',
	'settings_profile_avatar' => 'Аватар',
	'settings_profile_avatar_error' => 'Аватар жүктелмеді',
	'settings_profile_avatar_delete' => 'Жою',
	'settings_profile_avatar_change' => 'Аватарды өзгерту',
	'settings_profile_avatar_upload' => 'Аватар жүктеу',
	'settings_profile_avatar_resize_title' => 'Ауданын таңдау',
	'settings_profile_avatar_resize_apply' => 'Қабылдау',
	'settings_profile_avatar_resize_cancel' => 'Болдырмау',
	'settings_profile_foto' => 'Сурет',
	'settings_profile_foto_error' => 'Сурет жүктелмеді',
	'settings_profile_foto_delete' => 'Жою',
	'settings_profile_photo_change' => 'Суретті ауыстыру',
	'settings_profile_photo_upload' => 'Сурет жүктеу',
	'settings_profile_field_error_max' => 'Бірдей контакттарды %%count%% еседен артық жазуға болмайды',
	'settings_profile_submit' => 'Сақтау',
	'settings_profile_submit_ok' => 'Профайл сақталды',
	'settings_invite' => 'Шақыртуларды басқару',
	'settings_invite_notice' => 'Достарыңыз бен таныстарыңызды шақырғыңыз келсе, e-mail мекен-жайларын жазып, батырманы баса салыңыз',
	'settings_invite_available' => 'Қол жетімді',
	'settings_invite_available_no' => 'Қол жетімді шақырту жоқ әзірге',
	'settings_invite_used' => 'Қолданылғаны',
	'settings_invite_mail' => 'E-mail бойынша шақыру',
	'settings_invite_mail_error' => 'E-mail форматы қате',
	'settings_invite_mail_notice' => 'Бұл e-mail мекен-жайға тіркеуге шақырту жіберіледі',
	'settings_invite_many' => 'көп',
	'settings_invite_submit' => 'шақырту жіберу',
	'settings_invite_submit_ok' => 'Шақырту жіберілді',
	'settings_tuning' => 'Сайтты баптау',
	'settings_tuning_notice' => 'E-mail мекен-жайға ескерту',
	'settings_tuning_notice_new_topic' => 'блогқа жаңа мақала жазылса',
	'settings_tuning_notice_new_comment' => 'мақалаға жаңа пікір жазылса',
	'settings_tuning_notice_new_talk' => 'жаңа жеке хат келсе',
	'settings_tuning_notice_reply_comment' => 'пікіріңізге жауап жазылса',
	'settings_tuning_notice_new_friend' => 'сізді дос қатарына қосса',
	'settings_tuning_general' => 'Жалпы баптаулар',
	'settings_tuning_general_timeбаптауларды сақтау',
	'settings_tuning_submit_ok' => 'Баптаулар сақталды',
	'settings_account' => 'Аккаунт басптаулары',
	'settings_account_password' => 'Құпиясөз',
	'settings_account_password_notice' => 'Құпиясөзді өзгертпесеңіз, бұл жерге ештеңе жазбай-ақ қойыңыз.',
	'settings_account_submit' => 'Өзгертулерді сақтау',
	'settings_account_submit_ok' => 'Аккаунт сақталды',
	/**
	 * Баптаулар мәзірі
	 */
	'settings_menu' => 'Баптау',
	'settings_menu_profile' => 'Профайл',
	'settings_menu_tuning' => 'Сайтты баптау',
	'settings_menu_invite' => 'Шақыртулар',
	'settings_menu_account' => 'Аккаунт',
	/**
	 * Құпиясөзді қалпына келтіру
	 */
	'password_reminder' => 'Құпиясөзді қалпына келтіру',
	'password_reminder_email' => 'Сіздің e-mail',
	'password_reminder_submit' => 'Құпиясөзді өзгертетін сілтеме алу',
	'password_reminder_send_password' => 'Электронды поштаңызға жаңа құпиясөз жіберілді.',
	'password_reminder_send_link' => 'Электронды поштаңызға құпиясөзді өзгерту сілтемесі жіберілді',
	'password_reminder_bad_code' => 'Құпиясөзді өзгерту коды қате.',
	'password_reminder_bad_email' => 'Бұндай e-mail мекен-жайы бар қолданушы табылдмады',
	/**
	 * Панель
	 */
	'panel_b' => 'қалың',
	'panel_i' => 'қисайған',
	'panel_u' => 'асты сызылған',
	'panel_s' => 'асты сызылған',
	'panel_url' => 'сілтеме қою',
	'panel_url_promt' => 'Сілтемені жазыңыз',
	'panel_image_promt' => 'Сурет сілтемесін жазыңыз',
	'panel_code' => 'код',
	'panel_video' => 'видео',
	'panel_video_promt' => 'Видео сілтемесін жазыңыз',
	'panel_image' => 'сурет',
	'panel_cut' => 'кат',
	'panel_quote' => 'үзінді',
	'panel_list' => 'Тізім',
	'panel_list_ul' => 'UL LI',
	'panel_list_ol' => 'OL LI',
	'panel_list_li' => 'тізім пункті',
	'panel_title' => 'Тақырыбы',
	'panel_title_h4' => 'H4',
	'panel_title_h5' => 'H5',
	'panel_title_h6' => 'H6',
	'panel_clear_tags' => 'тегтерді тазарту',
	'panel_user' => 'қолданушы орналастыру',
	'panel_user_promt' => 'Қолданушы логинін жазыңыз',
	/**
	 * Блоктар
	 */
	'block_tags' => 'Тегтер',
	'block_tags_empty' => 'Тегтер жоқ',
	'block_tags_search' => 'Тег іздеу',
	'block_city_tags' => 'Қалалар',
	'block_country_tags' => 'Мемлекеттер',
	'block_blog_info' => 'Блог сипаттамасы',
	'block_blog_info_note' => 'Кеңес',
	'block_blog_info_note_text' => '<strong>Тег &lt;cut&gt; көлемді мақалаларды қысқартып</strong>, («Толығырақ») сілтемесі арқылы оқуға мүмкіндік береді.',
	'block_blogs' => 'Блогтар',
	'block_blogs_top' => 'Топ',
	'block_blogs_join' => 'Қосылғандар',
	'block_blogs_join_error' => 'Ұжымдық блогта жоқсыз',
	'block_blogs_self' => 'Менің',
	'block_blogs_self_error' => 'Жеке коллективті блогыңыз жоқ',
	'block_blogs_all' => 'Барлық блогтар',
	'block_stream' => 'Тікелей эфирлер',
	'block_stream_topics' => 'Жарияланғандар',
	'block_stream_topics_no' => 'Мақала жоқ.',
	'block_stream_comments' => 'Пікір',
	'block_stream_comments_no' => 'Пікірлер жоқ.',
	'block_stream_comments_all' => 'Барлық эфир',
	'block_friends' => 'Алушыларды достар арасынан таңдау',
	'block_friends_check' => 'Барлығын белгілеу',
	'block_friends_uncheck' => 'Белгіленгендерден алып тастау',
	'block_friends_empty' => 'Достар тізіміңіз бос',
	'site_history_back' => 'Артқа оралу',
	'site_go_main' => 'бастапқыға өту',
	/**
	 * іздеу
	 */
	'search' => 'іздеу',
	'search_submit' => 'Іздеу',
	'search_results' => 'іздеу нәтижесі',
	'search_results_empty' => 'Іздегеніңіз табылмады',
	'search_results_count_topics' => 'мақала',
	'search_results_count_comments' => 'пікір',
	/**
	 * Пошта
	 */
	'talk_menu_inbox' => 'Хат',
	'talk_menu_inbox_new' => 'Жаңалар',
	'talk_menu_inbox_list' => 'Хат тізімі',
	'talk_menu_inbox_create' => 'Хат жазу',
	'talk_menu_inbox_favourites' => 'Таңдаулы',
	'talk_menu_inbox_blacklist' => 'Құлыптау',
	'talk_inbox' => 'Пошталық жәшік',
	'talk_inbox_empty' => 'Бұнда ештеңе жоқ',
	'talk_inbox_target' => 'Алушы',
	'talk_inbox_title' => 'Тақырыбы',
	'talk_inbox_date' => 'Уақыт',
	'talk_inbox_make_read' => 'Оқылғар ретінде белгілеу',
	'talk_inbox_delete' => 'Белгіленгендерді өшіру',
	'talk_inbox_delete_confirm' => 'Хатты шынымен өшіресіз бе?',
	'talk_comments' => 'Пікірлер',
	'talk_comment_add_text_error' => 'Пікір тексті 2-3000 символ аралығында болуы керек',
	'talk_create' => 'Жаңадан',
	'talk_create_users' => 'Алушы',
	'talk_create_users_error' => 'Хатты кімге жібергіңіз келеді, соны жазыңыз',
	'talk_create_users_error_not_found' => 'Бұндай логинді қолданушы жоқ',
	'talk_create_users_error_many' => 'Алушылар көп',
	'talk_create_title' => 'Тақырыбы',
	'talk_create_title_error' => 'Хат тақырыбы 2-200 символ аралығында болуы керек',
	'talk_create_text' => 'Хат',
	'talk_create_text_error' => 'Хат тексті 2-3000 символ аралығында болсын',
	'talk_create_submit' => 'Жіберу',
	'talk_time_limit' => 'Хатты тым көп жібере беруге болмайды',
	'talk_favourite_inbox' => 'Таңдаулы хаттар',
	'talk_favourite_add' => 'таңдаулыға қосу',
	'talk_favourite_add_ok' => 'Хат таңдаулы қатарына қосылды',
	'talk_favourite_add_no' => 'Бұл хат таңдаулылар арасында жоқ',
	'talk_favourite_add_already' => 'Бұл хат таңдаулылар арасында бар',
	'talk_favourite_del' => 'таңдаулылар қатарынан өшіру',
	'talk_favourite_del_ok' => 'Таңдаулылар қатарынан өшті',
	'talk_favourite_empty' => 'Таңдаулылар қатарында хат жоқ',
	'talk_filter_title' => 'Хат іздеу',
	'talk_filter_erase' => 'Тазалау',
	'talk_filter_erase_form' => 'Форманы тазалау',
	'talk_filter_label_sender' => 'Жіберуші',
	'talk_filter_label_keyword' => 'Тақырып бойынша',
	'talk_filter_label_keyword_text' => 'Тексттен іздеу',
	'talk_filter_label_favourite' => 'Таңдаулылар қатарынан іздеу',
	'talk_filter_label_date' => 'Уақыт бойынша',
	'talk_filter_notice_sender' => 'Жіберуші логині',
	'talk_filter_notice_keyword' => 'Бір немесе бірнеше сөз жазыңыз',
	'talk_filter_notice_date' => 'Уақыт 25.12.2008 форматында жазылады',
	'talk_filter_submit' => 'Енгіземін',
	'talk_filter_submit_clear' => 'Тазалау',
	'talk_filter_error' => 'Фильтрлеу қатесі',
	'talk_filter_error_date_format' => 'Уақыт форматы дұрыс емес',
	'talk_filter_result_count' => 'Табылған хат: %%count%%',
	'talk_filter_result_empty' => 'Сіз қалаған нәтиже бойынша табылмады',
	'talk_user_in_blacklist' => 'Қолданушы <b>%%login%%</b> сізден хат қабылдамайды',
	'talk_blacklist_title' => 'Хат алғым келмейтін қолданушылар:',
	'talk_blacklist_empty' => 'Барлығынан қабылдау',
	'talk_balcklist_add_label' => 'Қолданушы қосу',
	'talk_balcklist_add_notice' => 'Бір немесе бірнеше логин жазыңыз',
	'talk_balcklist_add_submit' => 'Қабылдамау',
	'talk_blacklist_add_ok' => 'Қолданушы <b>%%login%%</b> қосылды',
	'talk_blacklist_user_already_have' => 'Қолданушы <b>%%login%%</b> black list арасында бар',
	'talk_blacklist_delete_ok' => 'Қолданушы <b>%%login%%</b> жойылды',
	'talk_blacklist_user_not_found' => 'Қолданушы <b>%%login%%</b> black list арасында жоқ',
	'talk_blacklist_add_self' => 'Өзіңізді black list қатарына қоса алмайсыз',
	'talk_speaker_title' => 'Хат алмасушылар',
	'talk_speaker_edit' => 'Тізімді өзгерту',
	'talk_speaker_add_label' => 'Қолданушы қосу',
	'talk_speaker_delete_ok' => 'Қолданушы <b>%%login%%</b> қосылды',
	'talk_speaker_user_not_found' => 'Қолданушы <b>%%login%%</b> хат алмасушылар арасында жоқ',
	'talk_speaker_user_already_exist' => ' <b>%%login%%</b> хат алмасушылар арасында бар',
	'talk_speaker_add_ok' => 'Қолданушы <b>%%login%%</b> қосылды',
	'talk_speaker_delete_by_self' => 'Қолданушы <b>%%login%%</b> бұл хатты өшірді',
	'talk_speaker_add_self' => 'Өзіңізді өзіңіз қоса алмайсыз',
	'talk_not_found' => 'Хат табылмады',
	/**
	 * Userfeed
	 */
	'userfeed_block_blogs_title' => 'Блогтар',
	'userfeed_block_users_title' => 'Амиголар',
	'userfeed_block_users_append' => 'Қосу',
	'userfeed_block_users_friends' => 'Достар',
	'userfeed_subscribes_already_subscribed' => 'Бұл қолданушының мақалаларына жазылғансыз',
	'userfeed_subscribes_updated' => 'Лента баптауы сақталды',
	'userfeed_get_more' => 'Толығырақ',
	'userfeed_title' => 'Лента',
	'userfeed_settings_note_follow_blogs' => 'Оқығыңыз келген блогтарды таңдаңыз',
	'userfeed_settings_note_follow_user' => 'Оқығыңыз келген мақала, адамдарды таңдаңыз',
	'userfeed_settings_note_follow_friend' => 'Оқығыңыз келген дос, мақалаларды таңдаңыз',
	'userfeed_no_subscribed_users' => 'Әлі ешкімнің мақалаларына жазылған жоқсыз',
	'userfeed_no_blogs' => 'Әлі ешқандай блогқа жазылған жоқсыз',
	'userfeed_error_subscribe_to_yourself' => 'Өз өзіңізге жазыла алмайсыз',
	/**
	 * Stream
	 */
	'stream_block_config_title' => 'Оқиғаларды баптау',
	'stream_block_users_title' => 'Адамдар',
	'stream_block_config_append' => 'Қосу',
	'stream_block_users_friends' => 'Достар',
	'stream_subscribes_already_subscribed' => 'Қолданушы жазбаларына жазылғансыз',
	'stream_subscribes_updated' => 'Лента баптаулары сақталды',
	'stream_get_more' => 'Толығырақ',
	'stream_event_type_add_wall' => 'Жеке параққа жазба қосу',
	'stream_event_type_add_topic' => 'Мақала қосу',
	'stream_event_type_add_comment' => 'Пікір қосу',
	'stream_event_type_add_blog' => 'Блог қосу',
	'stream_event_type_vote_topic' => 'Мақалаға дауысы',
	'stream_event_type_vote_comment' => 'Пікір дауысы',
	'stream_event_type_vote_blog' => 'Блог дауысы',
	'stream_event_type_vote_user' => 'Қолданушы дауысы',
	'stream_event_type_add_friend' => 'Достар қатары',
	'stream_event_type_join_blog' => 'Блогқа қосылу',
	'stream_no_subscribed_users' => 'Белсенділігін көргіңіз келген қолданушыға жазылған жоқсыз',
	'stream_no_events' => 'Белсенділік лентасы бос',
	'stream_error_subscribe_to_yourself' => 'Өз өзіңізге жазыла алмайсыз',
	'stream_list_user' => 'Қолданушы',
	'stream_list_event_add_wall' => 'жазба қалдырған парағы',
	'stream_list_event_add_topic' => 'қосқан жаңа мақаласы',
	'stream_list_event_add_blog' => 'қосқан жаңа блогы',
	'stream_list_event_add_comment' => 'пікір қалдырған мақаласы',
	'stream_list_event_vote_topic' => 'дауыс берген мақаласы',
	'stream_list_event_vote_blog' => 'бағалаған блогы',
	'stream_list_event_vote_user' => 'бағалаған қолданушысы',
	'stream_list_event_vote_comment' => 'бағалаған мақала пікірі',
	'stream_list_event_join_blog' => 'қосылған пікірі',
	'stream_list_event_add_friend' => 'дос қатарына қосқан қолданушы',

	'stream_list_event_add_wall_female' => 'жазба қалдырған парағы',
	'stream_list_event_add_topic_female' => 'қосқан жаңа мақаласы',
	'stream_list_event_add_blog_female' => 'қосқан жаңа блогы',
	'stream_list_event_add_comment_female' => 'пікір қалдырған мақаласы',
	'stream_list_event_vote_topic_female' => 'дауыс берген мақаласы',
	'stream_list_event_vote_blog_female' => 'бағалаған блогы',
	'stream_list_event_vote_user_female' => 'бағалаған қолданушысы',
	'stream_list_event_vote_comment_female' => 'бағалаған мақала пікірі',
	'stream_list_event_join_blog_female' => 'қосылған пікірі',
	'stream_list_event_add_friend_female' => 'дос қатарына қосқан қолданушы',

	'stream_menu' => 'Белсенділігі',
	'stream_menu_all' => 'Барлық мәзір',
	'stream_menu_user' => 'Қолданушы мәзірі',
	'stream_settings_note_filter' => 'Назарда ұстайтын әрекеттерді таңдаңыз',
	'stream_settings_note_follow_user' => 'Белсенділігін назарда ұстағыңыз келген қолданушыларды таңдаңыз',
	'stream_settings_note_follow_friend' => 'Белсенділігін назарда ұстағыңыз келген достарды таңдаңыз',
	/**
	 * Админка
	 */
	'admin_header' => 'Админка',
	'admin_list_plugins' => 'Плагиндерді басқару',
	'admin_list_userfields' => 'Қолданушы алаңшаларын басқару',
	'admin_list_restorecomment' => 'Пікірлер орындарын ауыстыру',
	'admin_list_recalcfavourite' => 'Таңдаулылар есебін жасау',
	'admin_list_recalcvote' => 'Дауыс есебін жасау',
	'admin_list_recalctopic' => 'Блог мақалаларын санау',
	/**
	 * Рейтинг TOP
	 */
	'top' => 'Рейтинг',
	'top_blogs' => 'TOP Блогтар',
	'top_topics' => 'TOP мақалалар',
	'top_comments' => 'TOP пікірлер',
	/**
	 * Тег бойынша іздеу
	 */
	'tag_title' => 'Тег бойынша іздну',
	/**
	 * Бетіне қарай
	 */
	'paging_next' => 'келесі',
	'paging_previos' => 'алдыңғы',
	'paging_last' => 'соңғы',
	'paging_first' => 'алғашқы',
	'paging' => 'Парақтар',
	/**
	 * Сурет жүктеу
	 */
	'uploadimg' => 'Сурет қою',
	'uploadimg_from_pc' => 'Компьютерден',
	'uploadimg_from_link' => 'Интернеттен',
	'uploadimg_file' => 'Файл',
	'uploadimg_file_error' => 'Файл жүктелмеді, типі мен өлшемін тексеріңіз',
	'uploadimg_url' => 'Сурет сілтемесі',
	'uploadimg_url_error_type' => 'Файл сурет типіне жатпайды',
	'uploadimg_url_error_read' => 'Ішкі файл оқылмай жатыр',
	'uploadimg_url_error_size' => 'Файл өлшемі 500кБ-тан жоғары',
	'uploadimg_url_error' => 'Сыртқы файл жүктелмей қалды',
	'uploadimg_align' => 'Түзету',
	'uploadimg_align_no' => 'жоқ',
	'uploadimg_align_left' => 'солға',
	'uploadimg_align_right' => 'оңға',
	'uploadimg_align_center' => 'ортасына',
	'uploadimg_submit' => 'Жүктеу',
	'uploadimg_link_submit_load' => 'Жүктеу',
	'uploadimg_link_submit_paste' => 'Сілтеме қою',
	'uploadimg_cancel' => 'Болдырмау',
	'uploadimg_title' => 'Сипаттамасы',
	/**
	 * Ескерту
	 */
	'notify_subject_comment_new' => 'Мақалаға жаңа пікір жазылды',
	'notify_subject_comment_reply' => 'Пікіріңізге жауап жазылды',
	'notify_subject_topic_new' => 'Блогқа жаңа мақала жазылды',
	'notify_subject_registration_activate' => 'Тіркелу',
	'notify_subject_registration' => 'Тіркелу',
	'notify_subject_invite' => 'Тіркелуге шақыру',
	'notify_subject_talk_new' => 'Жаңа хат келді',
	'notify_subject_talk_comment_new' => 'Хатқа жаңа пікір жазылды',
	'notify_subject_user_friend_new' => 'Сізді дос қатарына қосты',
	'notify_subject_blog_invite_new' => 'Сізді блогқа қосылуға шақырды',
	'notify_subject_reminder_code' => 'Құпиясөзді қалпына келтіру',
	'notify_subject_reminder_password' => 'Жаңа құпиясөз',
	'notify_subject_wall_reply' => 'Жеке парақтағы жазбаңызға жауап жазылды',
	'notify_subject_wall_new' => 'Жеке парағыңызға жазба қалдырылды',
	'notify_subject_reactvation' => 'Қайта мақұлдауға сұраныс',
	'notify_subject_user_changemail' => 'E-mail ауыстыруды мақұлдау',
	/**
	 * Админка
	 */
	'admin_title' => 'Админка',
	'admin_comment_restore_tree' => 'Пікірлер ауысты',
	'admin_favourites_recalculated' => 'Таңдаулылар есебі жасалды',
	'admin_votes_recalculated' => 'Дауыс беру есебі саналды',
	'admin_topics_recalculated' => 'Мақалалалар саны саналды',
	/**
	 * Плагиндерді басқару парағы
	 */
	'plugins_administartion_title' => 'Плагиндерді басқару',
	'plugins_plugin_name' => 'Атауы',
	'plugins_plugin_author' => 'Авторы',
	'plugins_plugin_version' => 'Нұсқасы',
	'plugins_plugin_action' => '',
	'plugins_plugin_activate' => 'Қосу',
	'plugins_plugin_deactivate' => 'Сөндіру',
	'plugins_plugin_settings' => 'Баптау',
	'plugins_unknown_action' => 'Орындалған әрекет белгісіз',
	'plugins_action_ok' => 'Орындалды',
	'plugins_activation_overlap' => 'Конфликт с активированным плагином. Ресурс %%resource%% переопределен на %%delegate%% плагином %%plugin%%.',
	'plugins_activation_overlap_inherit' => 'Конфликт с активированным плагином. Ресурс %%resource%% используется как наследник в плагине %%plugin%%.',
	'plugins_activation_file_not_found' => 'Файл плагина не найден',
	'plugins_activation_file_write_error' => 'Файл плагина не доступен для записи',
	'plugins_activation_version_error' => 'Для работы плагина необходимо ядро LiveStreet версии не ниже %%version%%',
	'plugins_activation_requires_error' => 'Для работы плагина необходим активированный плагин <b>%%plugin%%</b>',
	'plugins_submit_delete' => 'Удалить плагины',
	'plugins_delete_confirm' => 'Вы уверены, что желаете удалить указанные плагины?',
	/**
	 * Валидация данных
	 */
	'validate_string_too_long' => 'Поле %%field%% слишком длинное (максимально допустимо %%max%% символов)',
	'validate_string_too_short' => 'Поле %%field%% слишком короткое (минимально допустимо %%min%% символов)',
	'validate_string_no_lenght' => 'Поле %%field%% неверной длины (необходимо %%length%% символов)',
	'validate_email_not_valid' => 'Поле %%field%% не соответствует формату email адреса',
	'validate_number_must_integer' => 'Поле %%field%% должно быть целым числом',
	'validate_number_must_number' => 'Поле %%field%% должно быть числом',
	'validate_number_too_small' => 'Поле %%field%% слишком маленькое (минимально допустимо число %%min%%)',
	'validate_number_too_big' => 'Поле %%field%% слишком большое (максимально допустимо число %%max%%)',
	'validate_type_error' => 'Поле %%field%% должно иметь тип %%type%%',
	'validate_date_format_invalid' => 'Поле %%field%% имеет неверный формат даты',
	'validate_boolean_invalid' => 'Поле %%field%% должно быть %%true%% или %%false%%',
	'validate_required_must_be' => 'Поле %%field%% должно иметь значение %%value%%',
	'validate_required_cannot_blank' => 'Поле %%field%% не может быть пустым',
	'validate_url_not_valid' => 'Поле %%field%% не соответствует формату URL адреса',
	'validate_captcha_not_valid' => 'Поле %%field%% содержит неверный код',
	'validate_compare_must_repeated' => 'Поле %%field%% должно повторять %%compare_field%%',
	'validate_compare_must_not_equal' => 'Поле %%field%% не должно повторять %%compare_value%%',
	'validate_compare_must_greater' => 'Поле %%field%% должно быть больше чем %%compare_value%%',
	'validate_compare_must_greater_equal' => 'Поле %%field%% должно быть больше или равно %%compare_value%%',
	'validate_compare_must_less' => 'Поле %%field%% должно быть меньше чем %%compare_value%%',
	'validate_compare_must_less_equal' => 'Поле %%field%% должно быть меньше или равно %%compare_value%%',
	'validate_compare_invalid_operator' => 'У поля %%field%% неверный оператор сравнения %%operator%%',
	'validate_regexp_not_valid' => 'Поля %%field%% неверное',
	'validate_regexp_invalid_pattern' => 'У поля %%field%% неверное регулярное выражение',
	'validate_tags_count_more' => 'Поле %%field%% содержит слишком много тегов (максимально допустимо %%count%%)',
	'validate_tags_empty' => 'Поле %%field%% не содержит тегов, либо содержит неверные теги (размер тега допустим от %%min%% до %%max%% символов)',
	/**
	 * Подписка
	 */
	'subscribe_change_ok' => 'Жазылу өзгерісі жасалды',
	/**
	 * Toolbar
	 */
	'toolbar_scrollup_go' => 'Жоғары',
	'toolbar_topic_next' => 'Келесі мақала',
	'toolbar_topic_prev' => 'Алдығ,ы мақала',
	/**
	 * География
	 */
	'geo_select_country' => 'Мемлекет',
	'geo_select_region' => 'Облыс',
	'geo_select_city' => 'Қала',
	/**
	 * Избранное, общее
	 */
	'favourite_form_tags_button_save' => 'Сақтау',
	'favourite_form_tags_button_cancel' => 'Болдырмау',
	'favourite_form_tags_button_show' => 'тегтерді өзгерту',
	/**
	 * Инфо-блоки
	 */
	'infobox_blog_create' => 'Жасалған уақыты',
	'infobox_blog_topics' => 'Мақала',
	'infobox_blog_users' => 'Жазылушы',
	'infobox_blog_rating' => 'Рейтинг',
	'infobox_blog_limit_rating' => 'Жариялау шектеуі',
	'infobox_blog_topic_last' => 'Соңғы мақала',
	'infobox_blog_url' => 'Блогты оқу',
	'infobox_blog_rss' => 'RSS-ке жазылу',
	/**
	 * Создание
	 */
	'block_create' => 'Жаңадан',
	'block_create_topic_topic' => 'Мақала',
	'block_create_topic_question' => 'Сауалнама',
	'block_create_topic_link' => 'Сілтеме',
	'block_create_topic_photoset' => 'Фотосет',
	'block_create_blog' => 'Блог',
	'block_create_talk' => 'Хат',
	/**
	 * Описание HTML тегов
	 */
	'tags_help_link_show' => 'html-тегтер қол жетімді',
	'tags_help_special' => 'арнайы тегтер',
	'tags_help_special_cut' => 'Үлкен мақалаларды жалпы парақта кесіп тастап, "толығырақ" сілтемесі арқылы толық ашып оқуға мүмкіндік береді.',
	'tags_help_special_cut_name' => '"Толығырақ" сөзін басқа тіркеске ауыстыруға болады.',
	'tags_help_special_cut_name_example_name' => 'Толығырақ',
	'tags_help_special_video' => 'Келесі видеохостингтерді қолдайды: YouTube, RuTube, Vimeo және Я.Видео. <br/>Тегтер арасына видеоның тікелей сілтемесін ғана орналастырыңыз.',
	'tags_help_special_ls_user' => 'Текст арасына қолданушы атын орналастырады.',
	'tags_help_special_ls_user_example_user' => 'Ник',
	'tags_help_standart' => 'Стандартнты тегтер',
	'tags_help_standart_h' => 'Түрлі санаттағы тақырыптар өлшемі.',
	'tags_help_standart_img' => 'Сурет орналастыру, src атрибутына суреттің толық сілтемесін орналастыруға болады. Суретті align атрибуты арқылы түзетіп орналастыруға болады.',
	'tags_help_standart_a' => 'Сілтеме орналастыру, href атрибутынан соң кез-келген интернет мекен-жай, сайт бойынша аралайтын anchor орналастыруға болады.',
	'tags_help_standart_a_example_href' => 'Сілтеме',
	'tags_help_standart_b' => 'Текст қалың болады.',
	'tags_help_standart_i' => 'Текст қисайған болады.',
	'tags_help_standart_s' => 'Текст белінен сызылады.',
	'tags_help_standart_u' => 'Текст асты сызылады',
	'tags_help_standart_hr' => 'Горизонталды сызық.',
	'tags_help_standart_blockquote' => 'Текстті үзінді ету үшін, осы тегті қолданыңыз.',
	'tags_help_standart_table' => 'Кесте салу тегтері. Тег &lt;td&gt; кесте ұяшығы, тег &lt;th&gt; - тақырып ұяшығы, &lt;tr&gt; - кесте жолы. Кестенің барлық мазмұнын &lt;table&gt; тегіне салыңыз.',
	'tags_help_standart_ul' => 'Нөмірленбеген тізім; тізімнің әр элементі &lt;li&gt; тегімен белгіленеді, тізімнің барлық мазмұнын &lt;ul&gt; тегіне салыңыз.',
	'tags_help_standart_ol' => 'Нөмірленген тізім; тізімнің әр элементі &lt;li&gt; тегімен белгіленеді, тізімнің барлық мазмұнын &lt;ol&gt; тегіне салыңыз.',
	/**
	 * Системные сообщения
	 */
	'system_error_event_args' => 'Оқиғаны орналастыру кезіндегі сан аргументі қате',
	'system_error_event_method' => 'Қойылатын оқиға әдісі табылдмады',
	'system_error_404' => 'Бұндай парақ жоқ. Бет өшірілген немесе ешқашан болмаған.',
	'system_error_module' => 'Модуль класы табылмады',
	'system_error_module_no_method' => 'Модульде бұл әдіс жоқ',
	'system_error_cache_type' => 'Кештеу типі қате',
	'system_error_template' => 'Шаблон табылмады',
	'system_error_template_block' => 'Қосылатын блок шаблоны табылмады',
	'error' => 'Қате',
	'attention' => 'Назар аударыңыз',
	'system_error' => 'Жүйелік қате, қайта көріңіз',
	'exit' => 'Шығу',
	'need_authorization' => 'Сайтқа кіріңіз!',
	'or' => 'немесе',
	'window_close' => 'жабу',
	'not_access' => 'Кіру мүмкін емес',
	'install_directory_exists' => 'Сайтпен жұмыс істеу үшін /install бумасын жойыңыз.',
	'login' => 'Сайтқа кіру',
	'delete' => 'Жою',
	'date_day' => 'күні',
	'date_month' => 'айы',
	'month_array' => array(
		1 => array('қаңтар', 'қаңтар', 'қаңтар'),
		2 => array('ақпан', 'ақпан', 'ақпан'),
		3 => array('наурыз', 'наурыз', 'наурыз'),
		4 => array('сәуір', 'сәуір', 'сәуір'),
		5 => array('мамыр', 'мамыр', 'мамыр'),
		6 => array('маусым', 'маусым', 'маусым'),
		7 => array('шілде', 'шілде', 'шілде'),
		8 => array('тамыз', 'тамыз', 'тамыз'),
		9 => array('қыркүйек', 'қыркүйек', 'қыркүйек'),
		10 => array('қазан', 'қазан', 'қазан'),
		11 => array('қараша', 'қараша', 'қараша'),
		12 => array('желтоқсан', 'желтоқсан', 'желтоқсан'),
	),
	'date_year' => 'жыл',
	'date_now' => 'Жаңа ғана',
	'date_today' => 'Бүгін',
	'date_yesterday' => 'кеше',
	'date_tomorrow' => 'Ертең',
	'date_minutes_back' => '%%minutes%% минут бұрын; %%minutes%% минут бұрын; %%minutes%% минут бұрын',
	'date_minutes_back_less' => 'Минут болған жоқ',
	'date_hours_back' => '%%hours%% сағат бұрын; %%hours%% сағат бұрын; %%hours%% сағат бұрын',
	'date_hours_back_less' => 'Сағат болған жоқ',
	'today' => 'Бүгін',
	'more' => 'басқа',

	'timezone_list'=> array(
		'-12' => '[UTC − 12] Уақыт ауысу меридианы (батыс)',
		'-11' => '[UTC − 11] Мидуэй аралы, Самоа',
		'-10' => '[UTC − 10] Гавайи',
		'-9.5' => '[UTC − 9:30] Маркиз аралы',
		'-9' => '[UTC − 9] Аляска',
		'-8' => '[UTC − 8] Тынық мұхиты уақыт белдеуі (АҚШ және Канада) және Тихуана',
		'-7' => '[UTC − 7] Аризона',
		'-6' => '[UTC − 6] Мехико, Орталық Америка, Орталық уақыты (АҚШ және Канада)',
		'-5' => '[UTC − 5] Индиана (шығыс), Шығыс уақыты (АҚШ және Канада)',
		'-4.5' => '[UTC − 4:30] Венесуэла',
		'-4' => '[UTC − 4] Сантьяго, Атланта уақыты (Канада)',
		'-3.5' => '[UTC − 3:30] Ньюфаундленд',
		'-3' => '[UTC − 3] Бразилия, Гренландия',
		'-2' => '[UTC − 2] Ортаатлантика уақыты',
		'-1' => '[UTC − 1] Азор аралдары, Жасыл мыс аралдары',
		'0' => '[UTC] Гринвич уақыты: Дублин, Лондон, Лиссабон, Эдинбург',
		'1' => '[UTC + 1] Берлин, Мадрид, Париж, Рим, Батыс Орталық Африка',
		'2' => '[UTC + 2] Афины, Вильнюс, Киев, Рига, Таллин, Орталық Африка',
		'3' => '[UTC + 3] Калининград, Минск',
		'3.5' => '[UTC + 3:30] Тегеран',
		'4' => '[UTC + 4] Волгоград, Мәскеу, Самара, Санкт-Петербург, Баку, Ереван, Тбилиси',
		'4.5' => '[UTC + 4:30] Кабул',
		'5' => '[UTC + 5] Исламабад, Карачи, Орынбор, Ташкент',
		'5.5' => '[UTC + 5:30] Бомбей, Калькутта, Мадрас, Нью-Дели',
		'5.75' => '[UTC + 5:45] Катманду',
		'6' => '[UTC + 6] Екатеринбург, Алматы, Астана',
		'6.5' => '[UTC + 6:30] Рангун',
		'7' => '[UTC + 7] Бангкок, Новосибирск, Омбы',
		'8' => '[UTC + 8] Гонконг, Красноярск, Бейжің, Сингапур',
		'8.75' => '[UTC + 8:45] Оңтүстік-шығыс Батыс Австралия',
		'9' => '[UTC + 9] Токио, Сеул, Иркутск',
		'9.5' => '[UTC + 9:30] Дарвин',
		'10' => '[UTC + 10] Чита, Якутск, Канберра, Мельбурн, Сидней',
		'10.5' => '[UTC + 10:30] Лорд-Хау',
		'11' => '[UTC + 11] Владивосток, Соломоновы а-ы',
		'11.5' => '[UTC + 11:30] Норфолк Аралдары',
		'12' => '[UTC + 12] Камчатка, Магадан, Сахалин, Новая Зеландия, Фиджи',
		'12.75' => '[UTC + 12:45] Чатем Аралдары',
		'13' => '[UTC + 13] Феникс, Тонга аралдары',
		'14' => '[UTC + 14] Лайн аралдары'
	)
);
?>
